apiVersion: v1
kind: Service
metadata:
  name: attendancesystem-service
spec:
  selector:
    app: attendancesystem
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
